Tarzol.WebUI/Models/ProductAddViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tarzol.Entity;

namespace Tarzol.WebUI.Models
{
    public class ProductAddViewModel
    {
        public List<Product> Products { get; set; }
        public List<ProductColor> ProductColors { get; set; }
        public List<ProductSize> ProductSizes { get; set; }
        public List<Category> Categories { get; set; }
        public List<SubCategory> SubCategories { get; set; }
        public List<CategoryAndSubCategory> CategoryAndSubCategories { get; set; }
        public Product Product { get; set; }
    }
}

Tarzol.WebUI/Areas/Admin/Controllers/SellerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tarzol.Business.Abstract;
using Tarzol.DataAccess.Context;

namespace Tarzol.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SellerController : Controller
    {
        TarzolDbContext _tarzolDbContext;
        ISellerService _sellerService;

        public SellerController(TarzolDbContext tarzolDbContext, ISellerService sellerService)
        {
            _tarzolDbContext = tarzolDbContext;
            _sellerService = sellerService;
        }

        public IActionResult Index()
        {
            var seller = _sellerService.GetListAll();
            return View(seller);
        }

        public IActionResult ActiveSeller()
        {
            var activeSeller = _sellerService.GetListAll(i => i.Status == Core.Enums.Status.Active);
            return View(activeSeller);
        }
        public IActionResult SellerActiveAndPassive(int sellerId,string returnUrl)
        {
            var seller = _sellerService.GetBy(sellerId);
            if (seller.Status == Core.Enums.Status.Active)
            {
                seller.Status = Core.Enums.Status.Passive;
            }
            else
            {
                seller.Status = Core.Enums.Status.Active;
            }

            _sellerService.Update(seller);
            return Redirect(returnUrl);
        }

        public IActionResult PassiveSeller()
        {
            var passiveSeller = _sellerService.GetListAll(i => i.Status == Core.Enums.Status.Passive);
            return View(passiveSeller);
        }

        public IActionResult UnapprovedSeller()
        {
            var unapprovedSeller = _sellerService.GetListAll(i => i.Status == Core.Enums.Status.UnApproved);
            return View(unapprovedSeller);
        }
        public IActionResult Approval(int sellerId)
        {
            var seller = _sellerService.GetBy(sellerId);
            seller.Status = Core.Enums.Status.Active;
            _sellerService.Update(seller);
            return RedirectToAction("UnapprovedSeller");
        }

        public IActionResult SellerDetail(int sellerId)
        {
            var seller = _sellerService.GetBy(sellerId);
            var sellerCity = _tarzolDbContext.Cities.Where(i => i.ID == seller.CityID).FirstOrDefault();
            var sellerDistrict = _tarzolDbContext.Districts.Where(i => i.ID == seller.DistrictID).FirstOrDefault();
            ViewBag.sellerCity = sellerCity.CityName;
            ViewBag.sellerDistrict = sellerDistrict.DistrictName;
            return View(seller);
        }
    }
}

Tarzol.WebUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tarzol.Entity;
using Tarzol.WebUI.Models;
using Tarzol.DataAccess.Context;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Tarzol.WebUI.Controllers
{
    public class CartController : Controller
    {
        IHttpContextAccessor _httpContextAccessor;
        TarzolDbContext _tarzolDbContext;

        public CartController(IHttpContextAccessor httpContextAccessor, TarzolDbContext tarzolDbContext)
        {
            _httpContextAccessor = httpContextAccessor;
            _tarzolDbContext = tarzolDbContext;
        }

        public IActionResult Index()
        {            
            var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");           
            ViewBag.cart = cart;

            var productList = _tarzolDbContext.Products.ToList();
            return View(productList);
        }

        private int isExist(int id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].ProductID.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }

        public IActionResult Buy(int id)
        {
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart")==null)
            {
                List<CartItem> cart = new List<CartItem>();
                cart.Add(new CartItem { ProductID = id, Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if (index!=-1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new CartItem { ProductID = id, Quantity = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Remove(int id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }
        public IActionResult QuantityIncrease(int id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = isExist(id);
            if (index != -1)
            {
                cart[index].Quantity++;
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }

            return RedirectToAction("Index");
        }
        public IActionResult QuantityDecrease(int id)
        {
            List<CartItem> cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = isExist(id);
            if (index != -1)
            {
                if (cart[index].Quantity!=1)
                {
                    cart[index].Quantity--;
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                }
                
            }
            return RedirectToAction("Index");
        }

        //public IActionResult AddToCart(int Id,string returnUrl)
        //{
        //    var product = _tarzolDbContext.Products.FirstOrDefault(i => i.ID == Id);
        //    if (product != null)
        //    {
        //        GetCart().AddProduct(product, 1);

        //    }
        //    return Redirect(returnUrl);



        //    var cart = new List<CartItem>();
        //    var product = _tarzolDbContext.Products.FirstOrDefault(i => i.ID == Id);
        //    cart.Add(new CartItem()
        //    {
        //        Product = product,
        //        Quantity = 1
        //    });
        //    _httpContextAccessor.HttpContext.Session.SetString("Cart", "cart");
        //    return Redirect(returnUrl);


        //    var product = _tarzolDbContext.Products.FirstOrDefault(i => i.ID == Id);
        //    var cart = SessionHelper.Get<CartItem>(HttpContext.Session,"Cart");
        //    if (cart==null)
        //    {
        //        cart = new CartItem
        //        {
        //            Product=product,
        //            Quantity=1
        //        };

        //        SessionHelper.Set<CartItem>(HttpContext.Session,"Cart", cart);

        //        //SessionHelper.SetObjectAsJson(HttpContext.Session, "Cart", cart);
        //    }
        //    return Redirect(returnUrl);
        //}


        //public Cart GetCart()
        //{
        //    var cart = SessionHelper.GetObjectFromJson<Cart>(HttpContext.Session, "Cart");
        //    if (cart == null)
        //    {
        //        cart = new Cart();
        //        SessionHelper.SetObjectAsJson(HttpContext.Session, "Cart", "cart");
        //    }

        //    return ;

        //}


        //public IActionResult RemoveFromCart(int Id, string returnUrl)
        //{
        //    var product = _tarzolDbContext.Products.FirstOrDefault(i => i.ID == Id);
        //    if (product != null)
        //    {
        //        GetCart().DeleteProduct(product);
        //    }
        //    return Redirect(returnUrl);
        //}




    }
}

Tarzol.WebUI/Views/Seller/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="main">
    <div class="container">

        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40" style="margin-top:20px;">

            @await Html.PartialAsync("LeftMenu")

            <div class="col-md-8" style="margin-left:40px;">
                <div class="row">
                    <div class="col-md-5">
                        <div class="card-body text-center">
                            <p style="color:black;">
                                Bugünkü Satışım<br />
                                18.954+KDV
                            </p>
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5">
                        <div class="card-body text-center">
                            <p style="color:black;">
                                Son 7 Günlük Satışım<br />
                                18.954+KDV
                            </p>
                        </div>
                    </div>
                </div>


                <div class="row" style="margin:40px;">

                </div>

                <div class="row">
                    <div class="col-md-5">
                        <div class="card-body text-center">
                            <p style="color:black;">
                                Son 30 Günlük Kazancım<br />
                                18.954+KDV
                            </p>
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5">
                        <div class="card-body text-center">
                            <p style="color:black;">
                                Toplam Kazancım<br />
                                18.954+KDV
                            </p>
                        </div>
                    </div>
                </div>
            </div>







        </div>
    </div>
</div>







    <style>
        .col-md-5 {
            background-color:#fff;
            margin:auto;
            height:120px;
            border-radius:9px !important;
            box-shadow: 2px 2px 6px #000;            
        }
            .col-md-5:hover {
                -ms-transform: scale(1.1); 
                -webkit-transform: scale(1.1);
                transform: scale(1.1);
            }
        .card-body {
            text-align: center;
            width: 100%;
            height: 100%;
            padding: 40px;
        }
    </style>

Tarzol.WebUI/Views/Seller/LeftMenu.cshtml
            <!-- BEGIN SIDEBAR -->
            <div class="sidebar col-md-3 col-sm-5">
                <ul class="list-group margin-bottom-25 sidebar-menu">
                    <li class="list-group-item clearfix"><a asp-action="Index" asp-route-userName="@User.Identity.Name"><i class="glyphicon glyphicon-home"></i>&nbsp; ANA SAYFA</a></li>
                    <li class="list-group-item clearfix dropdown">
                        <a href="shop-product-list.html" class="collapsed">
                            <i class="glyphicon glyphicon-chevron-right"></i>
                            &nbsp;ÜRÜNLER

                        </a>
                        <ul class="dropdown-menu" style="display:block;">

                            <li><a asp-action="SellerProducts" asp-route-userName="@User.Identity.Name"><i class="glyphicon glyphicon-list-alt"></i> &nbsp;SATIŞTAKİ ÜRÜNLERİM</a></li>
                            <li><a asp-action="ProductAdd" asp-controller="Seller"><i class="glyphicon glyphicon-plus-sign"></i> &nbsp;ÜRÜN EKLE</a></li>
                            <li><a asp-action="PassiveProductList" asp-route-userName="@User.Identity.Name"><i class="glyphicon glyphicon-minus-sign"></i> &nbsp;PASİF ÜRÜNLER</a></li>

                        </ul>
                    </li>
                    <li class="list-group-item clearfix"><a asp-action="SellerAnswer" asp-route-userName="@User.Identity.Name"><i class="glyphicon glyphicon-question-sign"></i> &nbsp;SORU & CEVAP</a></li>
                    <li class="list-group-item clearfix"><a asp-action="ActiveOrder"><i class="glyphicon glyphicon-shopping-cart"></i> &nbsp;AKTİF SİPARİŞLER</a></li>
                    <li class="list-group-item clearfix"><a asp-action="DeliveredOrder"><i class="glyphicon glyphicon-ok"></i> &nbsp;TAMAMLANAN SİPARİŞLER</a></li>
                    <li class="list-group-item clearfix"><a href="shop-product-list.html"><i class="glyphicon glyphicon-alert"></i> &nbsp;İADELER</a></li>
                    <li class="list-group-item clearfix"><a href="shop-product-list.html"><i class="glyphicon glyphicon-bell"></i> &nbsp;BİLDİRİMLER</a></li>
                    <li class="list-group-item clearfix"><a href="shop-product-list.html"><i class="glyphicon glyphicon-envelope"></i> &nbsp;MESAJLAR</a></li>
                    <li class="list-group-item clearfix"><a href="shop-product-list.html"><i class="glyphicon glyphicon-user"></i> &nbsp;PROFİL</a></li>



                </ul>

            </div>
        

Tarzol.WebUI/Views/Seller/ProductAdd.cshtml
@model ProductWithImageAdd
@{
    ViewData["Title"] = "ProductAdd";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="main">
    <div class="container">

        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40" style="margin-top:20px;">

            @await Html.PartialAsync("LeftMenu")
            <div class="col-md-9">
                <form asp-action="ProductAdd" asp-controller="Seller" method="post" style="margin:50px;" enctype="multipart/form-data" class="form-horizontal" asp-route-activename="@User.Identity.Name">
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Ürün Adı</label>
                            <input type="text" asp-for="ProductName" class="form-control" /><br />
                        </div>

                        <div class="col-sm-6">
                            <label>Marka</label>
                            <input type="text" asp-for="TradeMark" class="form-control" /><br />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Ürün Kodu</label>
                            <input type="text" asp-for="ProductCode" class="form-control" /><br />
                        </div>
                        <div class="col-sm-6">
                            <label>Stok Adeti</label>
                            <input type="text" asp-for="UnitsInStock" class="form-control" /><br />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Ürün Piyasa Fiyatı</label>
                            <input type="text" asp-for="MarketPrice" class="form-control" /><br />
                        </div>
                        <div class="col-sm-6">
                            <label>Tarzol'a Özel Fiyat</label>
                            <input type="text" asp-for="DiscountedPrice" class="form-control" /><br />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Ürün Rengi</label>
                            <select asp-items="ViewBag.Color" asp-for="ProductColorID" class="form-control">
                                <option value="">Renk Seçiniz</option>
                            </select><br />
                        </div>
                        <div class="col-sm-6">
                            <label>Ürün Bedeni</label>
                            <select asp-items="ViewBag.Size" asp-for="ProductSizeID" class="form-control">
                                <option value="">Beden Seçiniz</option>
                            </select><br />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label>Üst Kategori</label>
                            <select id="categoryid" asp-items="ViewBag.Kategori" asp-for="CategoryID" class="form-control">
                                <option value="">Kategori Seçiniz</option>
                            </select><br />
                        </div>
                        <div class="col-sm-6">
                            <label>Alt Kategori</label>
                            <select id="subcategoryid" asp-for="SubCategoryID" class="form-control">
                            </select><br />
                        </div>
                    </div>

                    <div class="form-group">
                        <label>Ürün Açıklaması</label>
                        <textarea asp-for="Description" class="form-control" cols="10" rows="4"></textarea><br />
                    </div>
                    <div class="form-group">
                        <label>Ürün Detay Bilgileri</label>
                        <textarea asp-for="ProductInformation" class="form-control" cols="10" rows="10"></textarea><br />
                    </div>

                    <div class="form-group">
                        <label>1.Resim</label>
                        <input type="file" name="ImageOne" /><br />
                    </div>
                    <div class="form-group">
                        <label>2.Resim</label>
                        <input type="file" name="ImageTwo" /><br />
                    </div>
                    <div class="form-group">
                        <label>3.Resim</label>
                        <input type="file" name="ImageThree" /><br />
                    </div>
                    <div class="form-group">
                        <label>4.Resim</label>
                        <input type="file" name="ImageFour" /><br />
                        <br />
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary form-control">Ürünü Oluştur</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

@section ScriptProductCategory{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#categoryid").change(function () {
                $("#subcategoryid").empty();
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("LoadSubCats")',
                    dataType: 'json',
                    data: { id: $("#categoryid").val() },
                    success: function (states) {
                        $("#subcategoryid").append('<option value="' + -1 + '">' + "Alt Özellik" + '</option>');
                        $.each(states, function (i, state) {
                            $("#subcategoryid").append('<option value="' + state.value + '">' + state.text + '</option>');
                        });
                    }
                });
            });
        });
    </script>
}

Tarzol.WebUI/Views/Seller/ProductAnswer.cshtml
@model AnswerOfTheQuestionModel
@{
    ViewData["Title"] = "ProductAnswer";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="main">
    <div class="container">

        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40" style="margin-top:20px;">

            @await Html.PartialAsync("LeftMenu")
            <div class="col-md-9">

                <form method="post" asp-action="ProductAnswer" asp-controller="Seller" asp-route-questionId="@Model.Question.ID" asp-route-productId="@Model.Question.ProductID">
                    <div class="form-group">
                        <label  title="Soru Id:">@Model.Question.ID</label><br />
                        
                    </div>
                    <div class="form-group">
                        <label>@Model.Question.ProductID</label><br />
                       
                    </div>
                    <div class="form-group">
                        <label>@Model.Question.CreatedBy</label><br />
                        
                    </div>
                    <div class="form-group">
                        <label>@Model.Question.CreatedDate</label><br />
                    </div>
                    <div class="form-group">
                        <label>@Model.Question.QuestionContent</label><br />
                    </div>
                    <div class="form-group">
                        <label>Cevabınızı Yazınız...</label>
                        <textarea asp-for="@Model.Answer.AnswerContent"></textarea><br />
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn form-control btn-primary rounded submit px-3" style="color:#e6400c;">Cevapla</button>
                        </div>
                </form>


                



            </div>

        </div>
    </div>
</div>

Tarzol.WebUI/Views/Seller/SellerAppRegister.cshtml
@model SellerSignUpViewModel
@{
    ViewData["Title"] = "SellerAppRegister";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<br />
<br />


<div style="position:relative;width:600px;height:auto;margin:auto;">
    <form class="btn-outline-primary" asp-action="SellerAppRegister"
          asp-controller="Seller" method="post">
        
        <div class="form-group">
            <strong style="font-size:20px;">Satıcı Başvuru Formu</strong>
        </div>
        <div class="form-group">
            <label>İsim</label>
            <input type="text" class="form-control" asp-for="FirstName">
        </div>

        <div class="form-group">
            <label>Soyisim</label>
            <input type="text" class="form-control" asp-for="LastName">
        </div>
        <div class="form-group">
            <label>Telefon Numarası</label>
            <input type="number" class="form-control" asp-for="PhoneNumber">
        </div>
        <div class="form-group">
            <label>Mail Adresi</label>
            <input type="email" class="form-control" asp-for="Email">
        </div>
        <div class="form-group">
            <label>Şifre</label>
            <input type="password" class="form-control" asp-for="Password">
        </div>
        <div class="form-group">
            <label>Şifre Tekrar</label>
            <input type="password" class="form-control" asp-for="ComfirmPassword">
        </div>
        
        <br />
        <br />
        <br />
        <button class="btn btn-primary" style="width:100%;" type="submit">Gönder</button>

    </form>
</div>
<br />
<br />
<br />
<br />
<br />
<br />

Tarzol.WebUI/Views/Seller/SellerPage.cshtml
@model SellerPageModel
@{
    ViewData["Title"] = "SellerPage";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="main">
    <div class="container">
        <div class="row margin-bottom-40">
            <div class="sidebar col-md-3 col-sm-5">
                <div class="sidebar-filter margin-bottom-25">
                    <div class="product-item">
                        <div class="pi-img-wrapper">
                            <a asp-action="SellerPage" asp-controller="Seller" asp-route-sellerId="@Model.Seller.ID">
                                <img src="~/ProductImage/SellerImage/@Model.Seller.ProfileImageUrl" class="img-responsive" alt="Berry Lace Dress">
                            </a>
                        </div>
                        <h3 style="text-align:center;"><a asp-action="SellerPage" asp-controller="Seller" asp-route-sellerId="@Model.Seller.ID"><strong>@Model.Seller.CompanyName</strong></a></h3>

                    </div>
                </div>

                <div class="sidebar-products clearfix">
                    <h2>Çok Satanlar</h2>
                    @foreach (var item in Model.BestProducts)
                    {
                        <div class="item">
                            <a asp-action="ViewProduct" asp-controller="Product" asp-route-id="@item.ID"><img src="~/ProductImage/Big/@item.ImageOne" alt="Some Shoes in Animal with Cut Out"></a>
                            <h3><a asp-action="ViewProduct" asp-controller="Product" asp-route-id="@item.ID">@item.ProductName.ToUpper()</a></h3>
                            <div class="price">@item.DiscountedPrice.ToString("0.00")TL</div>
                        </div>
                    }


                </div>
            </div>
            <div class="col-md-9 col-sm-7">
                <div class="row product-list">
                    @foreach (var item in Model.Products)
                    {

                        <!-- PRODUCT ITEM START -->
                        <div class="col-md-4 col-sm-6 col-xs-12" style="height:450px;">
                            <div class="product-item" style="height:430px;">
                                <div class="pi-img-wrapper">
                                    <img src="~/ProductImage/Big/@item.ImageOne" class="img-responsive" style="height:320px;" alt="Berry Lace Dress">
                                    <div>
                                        <a href="~/ProductImage/Big/@item.ImageOne" class="btn btn-default fancybox-button">Yakınlaştır</a>
                                        <a href="#product-pop-up-@item.ID" class="btn btn-default fancybox-fast-view">Görüntüle</a>
                                    </div>
                                </div>
                                <h3><a asp-action="ViewProduct" asp-controller="Product" asp-route-id="@item.ID"><strong>@item.TradeMark.ToUpper()</strong>&nbsp; @item.ProductName.ToUpper()</a></h3>
                                <div class="pi-price">@item.DiscountedPrice.ToString("0.00")TL</div>
                                <a asp-controller="Cart" asp-action="Buy" asp-route-Id="@item.ID" class="btn btn-default add2cart">SEPETE EKLE</a>
                            </div>
                        </div>
                        //////////////////////////////////////////////////////////
                        <div id="product-pop-up-@item.ID" style="display: none; width: 700px;">
                            <div class="product-page product-pop-up">
                                <div class="row">
                                    <div class="col-md-6 col-sm-6 col-xs-3">
                                        <div class="product-main-image">
                                            <img src="~/ProductImage/Big/@item.ImageOne" alt="Cool green dress with red bell" class="img-responsive">
                                        </div>
                                        <div class="product-other-images">
                                            <a href="javascript:;" class="active"><img alt="Berry Lace Dress" src="~/ProductImage/Big/@item.ImageTwo"></a>
                                            <a href="javascript:;"><img alt="Berry Lace Dress" src="~/ProductImage/Big/@item.ImageThree"></a>
                                            <a href="javascript:;"><img alt="Berry Lace Dress" src="~/ProductImage/Big/@item.ImageFour"></a>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-9">
                                        <h1>@item.ProductName.ToUpper()</h1>
                                        <div class="price-availability-block clearfix">
                                            <div class="price">
                                                <strong>@item.DiscountedPrice.ToString("0.00")<span>TL</span></strong>
                                                <em><span>@item.MarketPrice.ToString("0.00")</span>TL</em>
                                            </div>
                                            <div class="availability">
                                                Stok Durumu:  @if (item.UnitsInStock > 30)
                                                {
                                                    <strong>Mevcut</strong>
                                                }
                                                else if (item.UnitsInStock < 10)
                                                {
                                                    <strong style="color:red">Tükeniyor</strong>
                                                }
                                                else
                                                {
                                                    <strong style="color:orange">Azalıyor</strong>
                                                }
                                            </div>
                                        </div><br />
                                        <div class="description">
                                            <p>
                                                @item.Description
                                            </p>
                                        </div>
                                        <br /><br />
                                        <div class="product-page-cart">

                                            <a asp-controller="Cart" asp-action="Buy" asp-route-Id="@item.ID" class="btn btn-primary">Sepete Ekle</a>
                                            <a asp-action="ViewProduct" asp-controller="Product" asp-route-id="@item.ID" class="btn btn-default">ÜRÜN DETAYLARI</a>
                                        </div>
                                    </div>


                                </div>
                            </div>
                        </div>

                    }
                </div>
               
                
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>

</div>